sudo: required
language: node_js
node_js:
 - "5.1"
install:
 - npm install
before_script:
 - 'export CHROME_BIN=chromium-browser'
 - 'export DISPLAY=:99.0'
 - 'sh -e /etc/init.d/xvfb start'
script:
 - test